# **Visão Artificial** - Sistemas de Visão e Perceção

![Intro Image](Images/ai_cv_intro.png)

### **Computer Vision** é um domínio da **inteligência artificial** que permite a computadores **interpretar e tomar decisões** com base em **dados visuais**, mesmo em **ambientes dinâmicos**.  🚀

### Esta capacidade permite revolucionar as indústrias e melhorar a interação humana com a tecnologia. 🤖👨‍💻

---

## **1 - Introdução a Processamento de Imagem**

---

### **Introdução ao NumPy** ⚙️🧮

- NumPy é uma biblioteca Python utilizada para computação numérica. 
    - Fornece suporte para matrizes e arrays multi-dimensionais de grandes dimensões 
    - Coleção de funções matemáticas para operar nestes arrays de forma eficiente. 

É a base para muitas outras bibliotecas no ambiente de análise de dados Python.

#### **Arrays**

In [2]:
import numpy as np

simple_array = np.array([1, 2, 3, 4, 5])
print(simple_array)

# Aceder a elementos no meu array
print(simple_array[0])
print(simple_array[1])

[1 2 3 4 5]
1
2


#### **Operações**

In [5]:
import numpy as np

# Adicionar o valor 10 a cada elemento do meu array
result = simple_array + 10

print(result)

# Multiplicar por 2 cada elemento de cada 
result = simple_array * 2

print(result)

[11 12 13 14 15]
[ 2  4  6  8 10]


#### **Operação de Matrizes**

In [7]:
# Criar um array de 2D (Matriz) 
matrix = np.array([[1,2,3], [4, 5, 6]])
print(f"Matrix\n {matrix} \n")

simple_array = np.array([1,2,3])

result = np.matmul(matrix, simple_array)

print(f"Resultado: \n {result}")

Matrix
 [[1 2 3]
 [4 5 6]] 

Resultado: 
 [14 32]


#### **Criação de Arrays**

In [15]:
import numpy as np

# Create a 3x3 matrix of zeros
zeros_matrix = np.zeros((3,3)) 
print(zeros_matrix)

# Create a 2x2 matrix of ones
ones_matrix = np.ones((2,2))
print(ones_matrix)

# Create a 4x4 matrix filled with 7
seven_matrix = np.full([4,4], 7, dtype = int)
print(seven_matrix)

# Create an array of evenly spaced values from 0 to 9
range_array = np.arange(10)
print(range_array)

# Create an array of 10 values evenly spaced between 0 and 1
linspace_array = np.linspace(0, 10, 10)
print(linspace_array)

# Create a 3x3 matrix of random values between 0 and 1
random_matrix = np.random.rand(3,3)
print(random_matrix)

# Create a 3x3 matrix of random values from a normal distribution (mean=0, std=1)
random_norm_matrix = np.random.randn(3,3)
print(random_norm_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[0 1 2 3 4 5 6 7 8 9]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[[0.26904613 0.63168597 0.98780392]
 [0.3419525  0.93185875 0.1005274 ]
 [0.74175535 0.9802313  0.14525012]]
[[ 0.69168698  1.03165696 -0.89223237]
 [ 1.33717963 -0.61693375 -0.51333399]
 [ 1.45449934  1.12355595  0.326046  ]]


### **Introdução ao Open CV** 🔍📷👁️

A OpenCV (Open Source Computer Vision Library) é uma poderosa biblioteca de funções de programação destinada principalmente à visão artificial para processamento em tempo real. É desenvolvida em C++ e optimizada para desempenho, mas também fornece ligações para Python, tornando-a acessível a um público mais vasto.

![OpenCV Image](Images/opencv_logo.png)

- Instalação do Open CV ```pip install opencv-python```

In [4]:
import cv2
import numpy as np

# Load an image from file
image = cv2.imread(r'Images\opencv_logo.png')

cv2.imshow('Image', image)
cv2.waitKey(0)  # Wait indefinitely for a key press
cv2.destroyAllWindows()  # Close all OpenCV windows

---

#### Como criar uma imagem preta com 320x320 ?

In [5]:
black_img = np.zeros((320,320, 1), dtype='uint8')


cv2.imshow('Black Image', black_img)
cv2.waitKey(0)  
cv2.destroyAllWindows()  

#### Como desenhar um ponto branco (1 pixel) na imagem preta?

In [6]:

black_img[159,150:170] = 255


cv2.imshow('Black Image', black_img)
cv2.waitKey(0)  # Wait indefinitely for a key press
cv2.destroyAllWindows()  

#### Como desenhar um retângulo branco na imagem preta?

In [43]:
import numpy as np
import cv2

img_height, img_width = 320, 320
black_img = np.zeros((img_height, img_width))

# Definir as dimnesões do rectângulo
rectangle_width, rectangle_height = 150, 100

x_center = img_width//2
y_center = img_height//2

black_img[y_center-(rectangle_height//2), x_center-(rectangle_width//2) : x_center + (rectangle_width//2)] = 1
black_img[y_center-(rectangle_height//2): y_center+(rectangle_height//2), x_center+(rectangle_width//2)] = 1
black_img[y_center+(rectangle_height//2), x_center-(rectangle_width//2) : x_center+(rectangle_width//2)] = 1
black_img[y_center-(rectangle_height//2): y_center+(rectangle_height//2), x_center-(rectangle_width//2)] = 1

cv2.imshow('Black Image', black_img)
cv2.waitKey(0)  
cv2.destroyAllWindows()  


#### Existe uma maneira mais fácil e rápida de fazer um retângulo? ▭
- Sim e o Open CV ajuda bastante na aceleração destes processos de processamento de imagens com métodos tradicionais.
- Conheces o método ``cv2.rectangle`` ?

    - ````cv2.rectangle(image, start_point, end_point, color, thickness) ````

Podes saber mais [aqui](https://www.geeksforgeeks.org/python-opencv-cv2-rectangle-method/) 📚

In [46]:
import numpy as np
import cv2

img_height, img_width = 320, 320
rectangle_width, rectangle_height = 150, 100
x_center = img_width//2
y_center = img_height//2

black_img = np.zeros((img_height, img_width))

cv2.rectangle(black_img, (y_center-(rectangle_height//2), x_center-(rectangle_width//2)), (y_center+(rectangle_height//2), x_center+(rectangle_width//2)), 1, thickness=1)


cv2.imshow('Black Image', black_img)
cv2.waitKey(0)  
cv2.destroyAllWindows()  

In [51]:
import numpy as np
import cv2

img_height, img_width = 320, 320



rectangle_width, rectangle_height = 150, 100

black_img = np.zeros((img_height, img_width))

x_center = black_img.shape[1]//2
y_center = black_img.shape[0]//2

cv2.rectangle(black_img, (y_center-(rectangle_height//2), x_center-(rectangle_width//2)), (y_center+(rectangle_height//2), x_center+(rectangle_width//2)), 1, thickness=4)


cv2.imshow('Black Image', black_img)
cv2.waitKey(0)  
cv2.destroyAllWindows()  

#### Como desenhar uma circunferência? ⬤
- Conheces o método ``cv2.circle`` ?

    - ````cv2.circle(image, center_coordinates, radius, color, thickness) ````

Podes saber mais [aqui](https://www.geeksforgeeks.org/python-opencv-cv2-circle-method/?ref=header_search) 📚

In [2]:
import numpy as np
import cv2

img_height, img_width = 320, 320
black_image = np.zeros((img_height, img_width))

x_center = black_image.shape[1]//2
y_center = black_image.shape[0]//2

cv2.circle(black_image, (x_center,y_center), 50, 1, thickness=1)

cv2.imshow('Black Image', black_image)
cv2.waitKey(0)  
cv2.destroyAllWindows() 

#### Como desenhar uma linha ➖
- Conheces o método ``cv2.line`` ? 
    
    - ````cv2.line(image, start_point, end_point, color, thickness)````

Podes saber mais [aqui](https://www.geeksforgeeks.org/python-opencv-cv2-line-method/?ref=header_search) 📚

In [6]:
import numpy as np
import cv2

img_height, img_width = 320, 320
black_image = np.zeros((img_height, img_width))

x_center = black_image.shape[1]//2
y_center = black_image.shape[0]//2
line_length = 20

cv2.line(black_image, (x_center-line_length//2,y_center), (x_center+line_length//2, y_center) , 1, 1)

cv2.imshow('Black Image', black_image)
cv2.waitKey(0)  
cv2.destroyAllWindows() 

#### Como escrever texto numa imagem? 📝

- Conheces o método ``cv2.putText`` ?
    
    - ````cv2.putText(image, 'Hello World', coordinates, font, fontScale, color, thickness, cv2.LINE_AA)````

    Podes saber mais [aqui](https://www.geeksforgeeks.org/python-opencv-cv2-puttext-method/?ref=header_search) 📚

In [10]:
import numpy as np
import cv2

img_height, img_width = 320, 320
black_image = np.zeros((img_height, img_width))

x_center = black_image.shape[1]//2
y_center = black_image.shape[0]//2

cv2.putText(black_image, 'Hello World', (x_center-100, y_center), cv2.FONT_HERSHEY_TRIPLEX, 1.0, 1, 2)

cv2.imshow('Black Image', black_image)
cv2.waitKey(0)  
cv2.destroyAllWindows() 